### ISSUE TITLE
Upload to database w/ external source

### ISSUE THREAD

**Issue by thomashirtz** [ramnes/notion-sdk-py#112]
Hello,
I am struggling to upload to database from an external source, is there an issue with the object that I send? (I tried w/ and w/out [])

```
from notion_client import Client


token = ""
database_id = ""
url = ""

client = Client(auth=token)
client.pages.create(
    parent={'database_id': database_id},
    properties={
        'Title': [{'text': {'content': 'Testing upload'}}],
        "File": [{
            "files": [
                {
                    "type": "external",
                    "name": "pdf",
                    "external": url
                }
            ]
        }]
    },
)
```
`File` and `Title` exist, but it still doesn't work :/

```
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\notion_client\client.py", line 115, in _parse_response
    response.raise_for_status()
  File "C:\ProgramData\Anaconda3\lib\site-packages\httpx\_models.py", line 1508, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '400 Bad Request' for url 'https://api.notion.com/v1/pages'
For more information check: https://httpstatuses.com/400

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/Thomas/GitHub/notion-scholar/excluded/upload.py", line 12, in <module>
    client.pages.create(
  File "C:\ProgramData\Anaconda3\lib\site-packages\notion_client\api_endpoints.py", line 202, in create
    return self.parent.request(
  File "C:\ProgramData\Anaconda3\lib\site-packages\notion_client\client.py", line 187, in request
    return self._parse_response(response)
  File "C:\ProgramData\Anaconda3\lib\site-packages\notion_client\client.py", line 122, in _parse_response
    raise APIResponseError(response, body["message"], code)
notion_client.errors.APIResponseError: body failed validation. Fix one: body.properties.File[0].text should be defined, instead was `undefined`. body.properties.File[0].mention should be defined, instead was `undefined`. body.properties.File[0].equation should be defined, instead was `undefined`. body.properties.File[0].id should be defined, instead was `undefined`. body.properties.File[0].name should be defined, instead was `undefined`. body.properties.File[0].person should be defined, instead was `undefined`. body.properties.File[0].bot should be defined, instead was `undefined`. body.properties.File[0].file should be defined, instead was `undefined`. body.properties.File[0].external should be defined, instead was `undefined`.

Process finished with exit code 1

```

I got what to put for `File` here https://developers.notion.com/reference/property-value-object#files-property-values

If I do that:
```
    client = Client(auth=token)
    client.pages.create(
        parent={'database_id': database_id},
        properties={
            'Title': [{'text': {'content': 'Testing upload'}}],
        }
    )
```
It works just fine

Thanks!

**Comment by ramnes** [comment]
Let's keep it as a discussion in #110 for now and open an issue if it's really an issue on notion-sdk-py side.
