### ISSUE TITLE
Does it support "page" parent type?

### ISSUE THREAD

**Issue by trustmaster** [ramnes/notion-sdk-py#142]
I'm trying to create a page with parent of type `page`, e.g.:

```python
par = {
    "type": "page_id",
    "page_id": "some-uuid-here"
}

props = {
    "Name": {
        "title": [
            {
                "text": {
                    "content": "Tuscan kale"
                }
            }
        ]
    },
    "Description": {
        "rich_text": [
            {
                "text": {
                    "content": "A dark green leafy vegetable"
                }
            }
        ]
    }
}

notion.pages.create(parent=par, properties=props)
```

but I get validation errors every time, e.g.:

```
notion_client.errors.APIResponseError: body failed validation. Fix one:
body.parent.database_id should be defined, instead was `undefined`.
body.properties.Name should be not present, instead was `{"title":[{"text":{"content":"Tuscan kale"}}]}`.
body.properties.Description should be not present, instead was `{"rich_text":[{"text":{"content":"A dark green leafy ve...`.
```

If I set `database_id` in `parent` it complains that `type` must be `database`.

Any clue on how to create a page inside of the other page rather than a database?

**Comment by ramnes** [comment]
The validation error here suggests that you used `"type": "database"`. What's the error with `"type": "page_id"`?

**Comment by trustmaster** [comment]
I use exactly the code above, just page uuid is different. I don't use `"type": "database"`. Full output is

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/notion_client/client.py", line 116, in _parse_response
    response.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/httpx/_models.py", line 736, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '400 Bad Request' for url 'https://api.notion.com/v1/pages'
For more information check: https://httpstatuses.com/400

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/vladimir.sibirov/dev/trustmaster/gkeep2notion/./gkeep2notion.py", line 339, in <module>
    notion.pages.create(parent=par, properties=props)
  File "/usr/local/lib/python3.9/site-packages/notion_client/api_endpoints.py", line 197, in create
    return self.parent.request(
  File "/usr/local/lib/python3.9/site-packages/notion_client/client.py", line 192, in request
    return self._parse_response(response)
  File "/usr/local/lib/python3.9/site-packages/notion_client/client.py", line 124, in _parse_response
    raise APIResponseError(response, body["message"], code)
notion_client.errors.APIResponseError: body failed validation. Fix one:
body.parent.database_id should be defined, instead was `undefined`.
body.properties.Name should be not present, instead was `{"title":[{"text":{"content":"Tuscan kale"}}]}`.
body.properties.Description should be not present, instead was `{"rich_text":[{"text":{"content":"A dark green leafy ve...`.
```

**Comment by ramnes** [comment]
Alright, Notion's API errors are really getting funnier day after day. :)

It's unlikely that the problem comes from the client but there's always a chance, so let's investigate. First thing is to try a bare HTTP request with cURL or similar, to see if the problem comes from the client or the request itself ­– it could be either malformed or misinterpreted server-side.

Did you try that?

**Comment by trustmaster** [comment]
Not yet, I just was curios if anybody has come across something like this, because all of the examples that I found use `"type": "database"` as parent. I can try bare HTTP API one of the next days.

**Comment by ramnes** [comment]
Cool, thanks. If that can help, we do have one example in the codebase that uses `page_id` (but it creates a database, not a page):

https://github.com/ramnes/notion-sdk-py/blob/899c2574ab9922712900f2ae20acccd4e05e1bc4/examples/databases/create_database.py#L43-L84

**Comment by trustmaster** [comment]
Yeah, the issue is with Notion API itself, this is what I've got with cURL example:

```
{"object":"error","status":400,"code":"validation_error","message":"body failed validation. Fix one:\nbody.parent.database_id should be defined, instead was `undefined`.\nbody.properties.Name should be not present, instead was `{\"title\":[{\"text\":{\"content\":\"Tuscan Kale\"}}]}`.\nbody.properties.Description should be not present, instead was `{\"rich_text\":[{\"text\":{\"content\":\"A dark green leafy ve...`.\nbody.properties.Food group should be not present, instead was `{\"select\":{\"name\":\"Vegetable\"}}`.\nbody.properties.Price should be not present, instead was `{\"number\":2.5}`."}
```

**Comment by trustmaster** [comment]
I have found the answer in the [documentation](https://developers.notion.com/reference/page) for `properties`:

> If `parent.type` is `"page_id"` or `"workspace"`, then the only valid key is title.

So, this code works:

```python
par = {
    "type": "page_id",
    "page_id": "some-uuid-here"
}

props = {
    "title": [
        {
            "text": {
                "content": "Tuscan kale"
            }
        ]
    }
}

notion.pages.create(parent=par, properties=props)
```
