### ISSUE TITLE
Using "and" in filter results in notion_client.errors.APIResponseError: body failed validation

### ISSUE THREAD

**Issue by brookekelseyryan** [ramnes/notion-sdk-py#145]
```python
NOTION_TOKEN = os.getenv("NOTION_TOKEN")

# Initialize the client
notion = Client(auth=NOTION_TOKEN)
notion_object = notion.databases.query(
    **{
        "database_id": os.getenv("NOTION_DATABASE_ID"),
        "filter": {
            "and": [
                {"property": "Type",
                 "select": {
                     "equals": "Task"
                 },
                 },
                {
                    "property": "Status",
                    "multi-select": {
                        "does_not_contain": "Complete"
                    }
                }
            ]}
    }
)
```

used an "and" compound filter, directly from [the Notion API docs](https://developers.notion.com/reference/post-database-query-filter#compound-filter-object), and I got this error:
```
Traceback (most recent call last):
  File "/Users/brookeryan/Developer/notion-todoist-pytoh/venv/lib/python3.10/site-packages/notion_client/client.py", line 116, in _parse_response
    response.raise_for_status()
  File "/Users/brookeryan/Developer/notion-todoist-pytoh/venv/lib/python3.10/site-packages/httpx/_models.py", line 736, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '400 Bad Request' for url 'https://api.notion.com/v1/databases/76a10424dee4485db743c536d5d74898/query'
For more information check: https://httpstatuses.com/400

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/brookeryan/Developer/notion-todoist-pytoh/main.py", line 17, in <module>
    notion_object = notion.databases.query(
  File "/Users/brookeryan/Developer/notion-todoist-pytoh/venv/lib/python3.10/site-packages/notion_client/api_endpoints.py", line 132, in query
    return self.parent.request(
  File "/Users/brookeryan/Developer/notion-todoist-pytoh/venv/lib/python3.10/site-packages/notion_client/client.py", line 192, in request
    return self._parse_response(response)
  File "/Users/brookeryan/Developer/notion-todoist-pytoh/venv/lib/python3.10/site-packages/notion_client/client.py", line 124, in _parse_response
    raise APIResponseError(response, body["message"], code)
notion_client.errors.APIResponseError: body failed validation. Fix one:
body.filter.and[1].title should be defined, instead was `undefined`.
body.filter.and[1].rich_text should be defined, instead was `undefined`.
body.filter.and[1].number should be defined, instead was `undefined`.
body.filter.and[1].checkbox should be defined, instead was `undefined`.
body.filter.and[1].select should be defined, instead was `undefined`.
body.filter.and[1].multi_select should be defined, instead was `undefined`.
body.filter.and[1].status should be defined, instead was `undefined`.
body.filter.and[1].date should be defined, instead was `undefined`.
body.filter.and[1].people should be defined, instead was `undefined`.
body.filter.and[1].files should be defined, instead was `undefined`.
body.filter.and[1].url should be defined, instead was `undefined`.
body.filter.and[1].email should be defined, instead was `undefined`.
body.filter.and[1].phone_number should be defined, instead was `undefined`.
body.filter.and[1].relation should be defined, instead was `undefined`.
body.filter.and[1].created_by should be defined, instead was `undefined`.
body.filter.and[1].created_time should be defined, instead was `undefined`.
body.filter.and[1].last_edited_by should be defined, instead was `undefined`.
body.filter.and[1].last_edited_time should be defined, instead was `undefined`.
body.filter.and[1].formula should be defined, instead was `undefined`.
body.filter.and[1].rollup should be defined, instead was `undefined`.
body.filter.and[1].or should be defined, instead was `undefined`.
body.filter.and[1].and should be defined, instead was `undefined`.
```

**Comment by brookekelseyryan** [comment]
nevermind, sorry, I used the wrong filter. updated and worked:
```
notion_object = notion.databases.query(
    **{
        "database_id": os.getenv("NOTION_DATABASE_ID"),
        "filter": {
            "and": [
                {"property": "Type",
                 "select": {
                     "equals": "Task"
                 },
                 },
                {
                    "property": "Status",
                    "status": {
                        "does_not_equal": "Complete"
                    }
                }
            ]}
    }
)
```
